name: Bug Report
description: File a bug report
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        We will ask your first to check a few things :
  - type: checkboxes
    id: checks
    label: Preliminary Checks
    description: Before submitting this issue, please make sure tehe following
      stataments are TRUE
    options:
      - label: I use a modern operating system (Windows 7 with SP1 or newer)
        required: true
      - label: I use the latest version of UCheck available (stable or beta version)
        required: true
  - type: checkboxes
    id: beta
    label: Beta Version
    description: If you are reporting an issue with latest BETA version, please
      check the following checkbox
    options:
      - label: I am reporting an issue for UCheck BETA
        required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell use about the issue in detail
    validations:
      required: true
  - type: textarea
    id: ucheck-report
    attributes: null
    label: ucheck-report
    description: Please copy and paste any relevant log output. This will be
      automatically formatted into code, so no need for backticks.
    validations:
      required: true
  - type: dropdown
    id: reproductible
    attributes:
      label: Is the issue reproductible?
      options:
        - Yes
        - No
      default: 0
      validations:
        required: true
